-- MySQL Script generated by MySQL Workbench
-- 02/28/16 14:21:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_identificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_identificacion` (
  `tii_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tii_nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`tii_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `per_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `per_identificacion` VARCHAR(45) NULL COMMENT '',
  `per_apellido` VARCHAR(65) NULL COMMENT '',
  `per_nombre` VARCHAR(65) NULL COMMENT '',
  `per_edad` INT NULL COMMENT '',
  `per_tipoidentificacion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`per_id`)  COMMENT '',
  INDEX `fk_persona_tipo_identificacion1_idx` (`per_tipoidentificacion` ASC)  COMMENT '',
  CONSTRAINT `fk_persona_tipo_identificacion1`
    FOREIGN KEY (`per_tipoidentificacion`)
    REFERENCES `mydb`.`tipo_identificacion` (`tii_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `usu_login` VARCHAR(50) NULL COMMENT '',
  `usu_password` VARCHAR(50) NULL COMMENT '',
  `usu_estado` INT NULL COMMENT '',
  `usu_persona` INT NOT NULL COMMENT '',
  PRIMARY KEY (`usu_id`)  COMMENT '',
  INDEX `fk_usuario_persona1_idx` (`usu_persona` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`usu_persona`)
    REFERENCES `mydb`.`persona` (`per_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `pfl_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pfl_nombre` VARCHAR(45) NULL COMMENT '',
  `pfl_descripcion` VARCHAR(45) NULL COMMENT '',
  `pfl_estado` INT NULL COMMENT '',
  PRIMARY KEY (`pfl_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_perfil` (
  `usp_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `usp_usuario` INT NOT NULL COMMENT '',
  `usp_perfil` INT NOT NULL COMMENT '',
  `usp_estado` INT NULL COMMENT '',
  PRIMARY KEY (`usp_id`)  COMMENT '',
  INDEX `fk_usurol_usuario_idx` (`usp_usuario` ASC)  COMMENT '',
  INDEX `fk_usurol_rol1_idx` (`usp_perfil` ASC)  COMMENT '',
  CONSTRAINT `fk_usurol_usuario`
    FOREIGN KEY (`usp_usuario`)
    REFERENCES `mydb`.`usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usurol_rol1`
    FOREIGN KEY (`usp_perfil`)
    REFERENCES `mydb`.`perfil` (`pfl_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria_producto` (
  `cap_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cap_nombre` VARCHAR(50) NULL COMMENT '',
  `cap_descripcion` VARCHAR(300) NULL COMMENT '',
  PRIMARY KEY (`cap_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `pro_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pro_nombre` VARCHAR(65) NULL COMMENT '',
  `pro_precio` INT NULL COMMENT '',
  `pro_categoria` INT NOT NULL COMMENT '',
  `pro_puntuacion` INT NULL COMMENT '',
  PRIMARY KEY (`pro_id`)  COMMENT '',
  INDEX `fk_producto_categprod1_idx` (`pro_categoria` ASC)  COMMENT '',
  CONSTRAINT `fk_producto_categprod1`
    FOREIGN KEY (`pro_categoria`)
    REFERENCES `mydb`.`categoria_producto` (`cap_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `ven_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ven_fecha` DATE NULL COMMENT '',
  `ven_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ven_id`)  COMMENT '',
  INDEX `fk_venta_usuario1_idx` (`ven_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_venta_usuario1`
    FOREIGN KEY (`ven_usuario`)
    REFERENCES `mydb`.`usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalleventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalleventa` (
  `dev_id` INT NOT NULL COMMENT '',
  `dev_cantidad` INT NULL COMMENT '',
  `dev_venta` INT NOT NULL COMMENT '',
  `dev_producto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`dev_id`)  COMMENT '',
  INDEX `fk_detalleventa_venta1_idx` (`dev_venta` ASC)  COMMENT '',
  INDEX `fk_detalleventa_producto1_idx` (`dev_producto` ASC)  COMMENT '',
  CONSTRAINT `fk_detalleventa_venta1`
    FOREIGN KEY (`dev_venta`)
    REFERENCES `mydb`.`venta` (`ven_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalleventa_producto1`
    FOREIGN KEY (`dev_producto`)
    REFERENCES `mydb`.`producto` (`pro_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`busqueda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`busqueda` (
  `bus_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `bus_usuario` INT NOT NULL COMMENT '',
  `bus_categprod` INT NOT NULL COMMENT '',
  PRIMARY KEY (`bus_id`)  COMMENT '',
  INDEX `fk_busqueda_usuario1_idx` (`bus_usuario` ASC)  COMMENT '',
  INDEX `fk_busqueda_categprod1_idx` (`bus_categprod` ASC)  COMMENT '',
  CONSTRAINT `fk_busqueda_usuario1`
    FOREIGN KEY (`bus_usuario`)
    REFERENCES `mydb`.`usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_busqueda_categprod1`
    FOREIGN KEY (`bus_categprod`)
    REFERENCES `mydb`.`categoria_producto` (`cap_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sesion` (
  `ses_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ses_inicio` INT NULL COMMENT '',
  `ses_fin` INT NULL COMMENT '',
  `ses_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ses_id`)  COMMENT '',
  INDEX `fk_sesion_usuario1_idx` (`ses_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_sesion_usuario1`
    FOREIGN KEY (`ses_usuario`)
    REFERENCES `mydb`.`usuario` (`usu_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
